apiVersion: v1
kind: Service
metadata:
  name: codify-submit
  namespace: codify
spec:
  selector:
    app: codify-submit-label
  ports:
  - name: codify-submit-port
    port: 80
    targetPort: 8080
  type: NodePort
